"""Primera migracion

Revision ID: c4b7c489333a
Revises: 
Create Date: 2024-11-19 23:23:55.288123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4b7c489333a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Alumno',
    sa.Column('matricula', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('ape_pa', sa.Text(), nullable=True),
    sa.Column('ape_ma', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('grupo', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('Maestro',
    sa.Column('matricula', sa.String(length=8), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=True),
    sa.Column('ape_pa', sa.Text(), nullable=True),
    sa.Column('ape_ma', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('grupo', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('asitencia', sa.String(length=8), nullable=True),
    sa.Column('asistencia', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['asitencia'], ['Alumno.matricula'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asistencia')
    op.drop_table('Maestro')
    op.drop_table('Alumno')
    # ### end Alembic commands ###
